# ==========================================================================
# LocalOracle - CRE Workflow Settings
# ==========================================================================
# Prediction Market Resolution Oracle for Chainlink Convergence Hackathon 2026
# Multi-source weather oracle with AI adjudication + on-chain settlement

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "localoracle-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: ""

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "localoracle-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: ""
